
#define FP_POINTING_SCROLLING_LAYER_ENABLE
#define FP_POINTING_SCROLLING_LAYER 4
#define FP_POINTING_DEFAULT_DPI 120
#define FP_POINTING_MAX_DPI 120

#define TAPPING_TERM 190
#define PERMISSIVE_HOLD

