
#define FP_POINTING_SCROLLING_LAYER_ENABLE
#define FP_POINTING_SCROLLING_LAYER 3
#define FP_POINTING_DEFAULT_DPI 120
#define FP_POINTING_MAX_DPI 120

#define TAPPING_TERM 150
#define PERMISSIVE_HOLD

